### ISSUE TITLE
Classes with webpack

### ISSUE THREAD

**Issue by Mathew78540** [tom-s/react-drag-sortable#18]
Hello,

I using webpack for my less, and when i try to put into my less :
```css
.draggable {
  background-color: yellow;
  margin: 10px;
}

.dragged {
  opacity: 0.7 !important;
}

.placeholder {
  opacity: 0.5;
}
```

They are not used, because css-loader rename class. Have you a solution ?
